export const APP_LOGIN = 'APP_LOGIN'
export const APP_LOGOUT = 'APP_LOGOUT'
export const APP_SET_USER = 'APP_SET_USER'
export const APP_LOGIN_FAILED = 'APP_LOGIN_FAILED'

export const APP_SCRIPT = 'APP_SCRIPT'

export const APP_LEFT_BAR    = 'APP_LEFT_BAR'
export const APP_ONE_SIGNAL    = 'APP_ONE_SIGNAL'

export const PROJECTS_LOADING = 'PROJECTS_LOADING'
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS'
export const PROJECTS_FAILED = 'PROJECTS_FAILED'

export const PROJECT_LOADING = 'PROJECT_LOADING'
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS'
export const PROJECT_FAILED = 'PROJECT_FAILED'

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS'
export const CATEGORIES_FAILED = 'CATEGORIES__FAILED'

export const CLASSIFIEDS_LOADING = 'CLASSIFIEDS_LOADING'
export const CLASSIFIEDS_SUCCESS = 'CLASSIFIEDS_SUCCESS'
export const CLASSIFIEDS_FAILED = 'CLASSIFIEDS__FAILED'

export const CLASSIFIED_LOADING = 'CLASSIFIED_LOADING'
export const CLASSIFIED_SUCCESS = 'CLASSIFIED_SUCCESS'
export const CLASSIFIED_FAILED = 'CLASSIFIED__FAILED'

export const REWRITE_LOADING = 'REWRITE_LOADING'
export const REWRITE_SUCCESS = 'REWRITE_SUCCESS'
export const REWRITE_FAILED = 'REWRITE__FAILED'

export const BEFORE_UPLOAD_IMAGE = 'BEFORE_UPLOAD_IMAGE'
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const UPLOAD_FAILD = 'UPLOAD_FAILD'
